In [3]:
import numpy as np

In [5]:
w=np.array([[1],[2],[3]])  
print(w.shape)

(3, 1)


In [7]:
y=np.array([[1],[-1],[1],[-1],[-1]])  
print(y.shape)

(5, 1)


In [9]:
x=np.array([[1,2,3],[1,2,83],[1,22,3],[1,2,-3],[10,20,30]])
print(x.shape)


(5, 3)


In [11]:
y_pred=x@w
print(y_pred)

[[ 14]
 [254]
 [ 54]
 [ -4]
 [140]]


In [12]:
y*x

array([[  1,   2,   3],
       [ -1,  -2, -83],
       [  1,  22,   3],
       [ -1,  -2,   3],
       [-10, -20, -30]])

In [17]:
y*x@w

array([[  14],
       [-254],
       [  54],
       [   4],
       [-140]])

In [18]:
(y*x )/(y*x@w)  # (5,3)

array([[ 0.07142857,  0.14285714,  0.21428571],
       [ 0.00393701,  0.00787402,  0.32677165],
       [ 0.01851852,  0.40740741,  0.05555556],
       [-0.25      , -0.5       ,  0.75      ],
       [ 0.07142857,  0.14285714,  0.21428571]])

In [20]:
np.sum((y*x )/(y*x@w) ,axis=0)

array([-0.08468733,  0.20099571,  1.56089864])

In [ ]:
#IMPORTANT: You can only use numpy here. Do not use any pre-made algorithms (e.g. Scikit-Learn's Logistic Regression)
class OurLogisticRegression:
    def __init__(self, lr: int, epochs: int, probability_threshold: float = 0.5, random_state = None):
        self.lr = lr # The learning rate
        self.epochs = epochs # The number of training epochs
        self.probability_threshold = probability_threshold # If the output of the sigmoid function is > probability_threshold, the prediction is considered to be positive (True)
                                                           # otherwise, the prediction is considered to be negative (False)
        self.random_state = random_state # The random state will be used set the random seed for the sake of reproducibility
    
    def _prepare_input(self, X):
        # Here, we add a new input with value 1 to each example. It will be multiplied by the bias
        ones = np.ones((X.shape[0], 1), dtype=X.dtype)
        return np.concatenate((ones, X), axis=1)
    
    def _prepare_target(self, y):
        # Here, we convert True to +1 and False to -1
        #TODO (Optional): You can modify your function if you wish to used other values for the positive and negative classes

        # Convert True values to 1 and False values to -1
        return np.where(y, 1, -1)

    def _initialize(self, num_weights: int, stdev: float = 0.01):
        # Here, we initialize the weights using a normally distributed random variable with a small standard deviation
        self.w = np.random.randn(num_weights) * stdev

    def _gradient(self, X, y):
        #TODO: Compute and return the gradient of the weights (self.w) wrt to the loss given the X and y arrays

        # 1- sigmoid(x)= 1/(1+e^x)

        N = np.shape(X)[0]
        # # Compute the dot product of W and X
        # z = np.dot(X, self.w)

        # # Compute the logistic function of z
        # sigma_z = sigmoid(-1*y * z)
        # print(sigma_z.shape)

        # y_x=(X.T * y).T #X  (402,9) y(402,)[Broadcasted] = (9, 402).T=(402,9)

        z= X@self.w.T  # (402,9)*(9,1) = (402, 1)
        sigma_z = sigmoid(y*z) #(402,1) (1/1+e^(yWtX))

        # (9, 402) / (402, 1) = 
        # (y * X.T / (1 + sigma_z) # (9,402)
        loss=(-1/N)*np.sum(y * X.T / (1 + sigma_z),axis=1)  #(9,)


        gradient_loss=(-1/N)*np.sum(  *(1-sigmoid(  )))  #(9,)

        return loss

    def _update(self, X, y):
        #TODO: Implement this function to apply a single iteration on the weights "self.w"
        #Hint: use self._gradient

        # Weight update Eq: w(t+1)=w(t)-lr * grad_w
        self.w=self.w - self.lr * self._gradient(X,y)
        return

    def fit(self, X, y):
        np.random.seed(self.random_state) # First, we set the seed
        X = self._prepare_input(X) # Then we prepare the inputs
        y = self._prepare_target(y) # and prepare the targets too
        self._initialize(X.shape[1]) # and initialize the weights randomly
        for _ in range(self.epochs): # Then we update the weights for a certain number of epochs
            self._update(X, y)
        return self # Return self to match the behavior of Scikit-Learn's LinearRegression fit()
    
    def predict(self, X):
        X = self._prepare_input(X)
        #TODO: Implement the rest of this function (Note: It should return a boolean array)

        # Eq: p(y|X)=sigmoid(WTX)
        sig=sigmoid(X@self.w)  #(batch_size,1) :D

        return sig>self.probability_threshold